const videos = [
    { fileName: "2021 - Al Horning.mp4", keywords: "" },
    { fileName: "2021 - Dorothy Jantzen.mp4", keywords: "" },
    { fileName: "2021 - Kelowna Spartans.mp4", keywords: "" },
    { fileName: "2021 - Roli and Sharon.mp4", keywords: "" },
    { fileName: "2021 - Scott Frandsen.mp4", keywords: "" },
    { fileName: "2019 - Tania Jones.mp4", keywords: "track and field, running" },
    { fileName: "2019 - Roger LaFontaine.mp4", keywords: "basketball, coach, builder" },
    { fileName: "2019 - Robyn Buna.mp4", keywords: "basketball" },
    { fileName: "2019 - Kelsey Serwa.mp4", keywords: "skiing, ski cross" },
    { fileName: "2019 - Duncan McNaughton.mp4", keywords: "track and field, high jump" },
    { fileName: "2019 - Daphne Richard.mp4", keywords: "horseback riding, builder" },
    { fileName: "2018 - Tracey Melesko.mp4", keywords: "track and field, skiiing" },
    { fileName: "2018 - Rob Dirk.mp4", keywords: "hockey" },
    { fileName: "2018 - Hugh Wong.mp4", keywords: "volleyball, coach, builder" },
    { fileName: "2018 - Heather Mandoli Alschular.mp4", keywords: "rowing" },
    { fileName: "2018 - Chad Folk.mp4", keywords: "football" },
    { fileName: "2018 - Allen Simpson.mp4", keywords: "baseball, pioneer, builder" },
    { fileName: "2017 - Western Canada Basketball Tournament.mp4", keywords: "basketball, bennett award" },
    { fileName: "2017 - Malindi Elmore.mp4", keywords: "track and field, running" },
    { fileName: "2017 - Kelowna Buckaroos.mp4", keywords: "hockey, pioneer" },
    { fileName: "2017 - Garett Hickling.mp4", keywords: "rugby" },
    { fileName: "2017 - Conrad Leinemann.mp4", keywords: "beach volleyball, volleyball" },
    { fileName: "2017 - Chris Taneda.mp4", keywords: "karate, martial arts, coach, builder" },
    { fileName: "2016 - Ron Rubadeau.mp4", keywords: "sailing, builder" },
    { fileName: "2016 - Kelly Scott.mp4", keywords: "Kelly Scott, Jeanna Scraeder, Sasha Carter, Renee Simons, Michelle Allan, Gerry Richard, curling, team" },
    { fileName: "2016 - Conny Stamhuis.mp4", keywords: "swimming" },
    { fileName: "2016 - Bob Giordano.mp4", keywords: "hockey, volunteer, builder" },
    { fileName: "2016 - Blair Horn.mp4", keywords: "rowing" },
    { fileName: "2015 - Wayne Hicks.mp4", keywords: "hockey, pioneer" },
    { fileName: "2015 - Sarah Charles.mp4", keywords: "gymnastics, trampoline" },
    { fileName: "2015 - Rod Belinski.mp4", keywords: "volleyball, coach, builder" },
    { fileName: "2015 - John & Jennifer Hindle.mp4", keywords: "triathalon, volunteer, bennett award" },
    { fileName: "2015 - Christi Van Hees.mp4", keywords: "Racquetball" },
    { fileName: "2014 - Van Tighems.mp4", keywords: "Mike Van Teigham, Brenda Van Teigham, track and field, coach, volunteer" },
    { fileName: "2014 - Glen Mervyn.mp4", keywords: "rowing" },
    { fileName: "2014 - Gillian Thomson.mp4", keywords: "sailing" },
    { fileName: "2014 - 04 Rockets.mp4", keywords: "2004, Kelowna Rockets, hockey" },
    { fileName: "2013 - Wayne North.mp4", keywords: "hockey, coach, volunteer" },
    { fileName: "2013 - Sutton Curling.mp4", keywords: "Julie Sutton, Judy Wood, Susan Auty, Marla Geiger, Dan Martell, curling, team" },
    { fileName: "2013 - Brock Aynsley.mp4", keywords: "football, track and field" },
    { fileName: "2013 - Blair Chapman.mp4", keywords: "hockey" },
    { fileName: "2012 - Okanagan Sun.mp4", keywords: "football, team" },
    { fileName: "2012 - Glenn Ennis.mp4", keywords: "rugby" },
    { fileName: "2012 - Erminia Russo.mp4", keywords: "volleyball" },
    { fileName: "2012 - Barry Urness.mp4", keywords: "football" },
    { fileName: "2012 - Alex Rescky.mp4", keywords: "football, hockey, soccer, volunteer, coach" },
    { fileName: "2011 - Lawrence Nagy.mp4", keywords: "football" },
    { fileName: "2011 - Joan Campbell.mp4", keywords: "golf" },
    { fileName: "2011 - Eric Tasker.mp4", keywords: "soccer" },
    { fileName: "2011 - Dan Bertoia.mp4", keywords: "track and field, running" },
    { fileName: "2011 - Aundrea Bertaio.mp4", keywords: "track and field, running" },
    { fileName: "2010 - Teddy Bears.mp4", keywords: "basketball" },
    { fileName: "2010 - Mervyn Andrews.mp4", keywords: "field hockey, coach" },
    { fileName: "2010 - Jay Christensen.mp4", keywords: "football" },
    { fileName: "2010 - Henry Tostenson.mp4", keywords: "baseball" },
    { fileName: "2010 - Don Arnold.mp4", keywords: "rowing" },
    { fileName: "2009 - JoAnne Ritchie.mp4", keywords: "triathalon" },
    { fileName: "2009 - Jack Brow.mp4", keywords: "track and field, football, soccer, hockey, volunteer, coach" },
    { fileName: "2009 - Folk Curling Team.mp4", keywords: "Rick Folk, Pat Ryan, Bert Gretzinger, Gerry Richard, curling, team" },
    { fileName: "2009 - Athans Family.mp4", keywords: "George Athans, Greg Athans, Gary Athans, Irene Athans, diving, swimming, skiing" },
    { fileName: "2008 - Kelowna Packers.mp4", keywords: "hockey" },
    { fileName: "2008 - 58 Packers Pictorial.mp4", keywords: "hockey" },
];
